export const ERROR = 'ERROR';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const ADD_PRODUCT_STARTED = 'ADD_PRODUCT_STARTED';
export const ADD_PRODUCT_SUCESS = 'ADD_PRODUCT_SUCESS';
export const ERROR_CLEAR = 'ERROR_CLEAR';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';
